services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    tty: true
    hostname: api
    working_dir: /app
    volumes:
      - .:/app
    container_name: algaworks-esr-algafood-api
    ports:
      - '8000:8000'
      - '8080:8080'
      - '35729:35729'
    environment:
      - SERVER_PORT=8080
    command: ./mvnw spring-boot:run -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,address=*:8000,server=y,suspend=n"