spring:
    application:
        name: algaworks-esr-algafood-api

    datasource:
        url: jdbc:postgresql://localhost:5432/algafood
        username: root
        password: ${ALGAFOOD_DATASOURCE_PASSWORD}
        driver-class-name: org.postgresql.Driver
    
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: create
             
        properties:
            hibernate:
                check-nullability: true
        show-sql: true