spring:
    application:
        name: algaworks-esr-algafood-api

    datasource:
        url: jdbc:postgresql://localhost:5432/algafood
        username: root
        password: ${ALGAFOOD_DATASOURCE_PASSWORD}
        driver-class-name: org.postgresql.Driver

        hikari:
            connectionTimeout: 30000
            maximum-pool-size: 5
            minimum-idle: 3
            idle-timeout: 10000
    
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: create
             
        properties:
            hibernate:
                check-nullability: true
        show-sql: true